[project]
name = "text-diffusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.1.1",
    "numpy>=2.3.3",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]
